# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Update package list and install necessary packages
      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack \
            arj cabextract device-tree-compiler liblzma-dev python3-pip brotli \
            liblz4-tool axel gawk aria2 detox cpio rename liblz4-dev curl python3-venv

      # Create a Python virtual environment and activate it
      - name: Set up Python environment and install packages
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install aospdtgen backports.lzma extract-dtb protobuf pycryptodome docopt zstandard

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
